替换值: ML1
省: ML2
市: ML3
区、县: ML4
街道、乡镇: ML5
社区、村: ML6
组: ML7
路: ML8
门牌号: ML9
POI: ML10
方位信息: ML11
楼号: ML12
单元、门: ML13
层: ML14
户号: ML15
运营商: ML4
商品一级类目: ML2
商品二级类目: ML3
商品三级类目: ML4
商品四级类目: ML5
推测性别: ML2
国家: ML4
类别: ML2
地区: ML2
名称: ML3
领域: ML4
组织形式: ML5
品牌: ML2
关键词: ML2

