package enum

/*."operation"."type"操作类型 枚举
TABLE_DELETE 表删除
TABLE_RENAME 表重命名
FIELD_MAPPING 字段映射
FIELD_TYPE 字段类型修改
FIELD_RENAME 字段重命名
FIELD_DELETE 字段删除
ROW_DELETE 行删除
CELL 单元格修改
CELL_BATCH 单元格批量修改
RULE_EXECUTE 规则执行
RULE_IGNORE 规则忽略
MODIFY_INVALID_VALUE 把无效值全量修改为NULL
REGULARIZE_FIELD_VALUE 全量规整字段值
*/

const (
	TABLE_DELETE  = "TABLE_DELETE"
	TABLE_RENAME  = "TABLE_RENAME"
	FIELD_MAPPING = "FIELD_MAPPING"
	FIELD_TYPE    = "FIELD_TYPE"
	FIELD_RENAME  = "FIELD_RENAME"
	FIELD_DELETE  = "FIELD_DELETE"
	ROW_DELETE    = "ROW_DELETE"
	CELL          = "CELL"
	CELL_BATCH    = "CELL_BATCH"
	RULE_EXECUTE  = "RULE_EXECUTE"
	//RULE_IGNORE   = "RULE_IGNORE"
	MODIFY_INVALID_VALUE   = "MODIFY_INVALID_VALUE"   //检测
	REGULARIZE_FIELD_VALUE = "REGULARIZE_FIELD_VALUE" //规整
)
