package enum

const (
	EXPORT_TASK             = "EXPORT_TASK"
	RULEDISCOVER_TASK       = "RULEDISCOVER_TASK"
	QUALITY_IMPROVEMENT     = "QUALITY_IMPROVEMENT"
	DATA_STANDARDIZATION    = "DATA_STANDARDIZATION"
	DATA_QUALITY_ASSESSMENT = "DATA_QUALITY_ASSESSMENT"
)
