# config.yml 默认配置文件

#gorm连接pg配置
pg_config:
  host: 192.168.15.204
  port: 5432
  user: rock
  password: rockPoD@2020
  dbname: rock_meta
  max_open_conns: 20
  max_idle_conns: 10

# 日志配置
logger_config:
  # 日志打印等级，[debug, info, warn, err, off]
  level: "debug"
  # 日志存放路径，当前目录的log文件夹
  path: "log"
  # 最大存放时间，180天，超过180天的日志会删除
  max_age: 180
  # 日志分割时间，单位小时，定义168为一周
  rotation_time: 168